---
- name: Sync to NetBox
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    netbox_url: "{{ lookup('env', 'NETBOX_URL') | default('http://127.0.0.1:8000', true) }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    netbox_site_mapping:
      dc1: "DC1_JULIO"
      dc2: "DC2_JULIO"
    netbox_reconcile: true
    netbox_verify_ssl: false
    # Async is enabled by default (netbox_use_async: true)
  tasks:
    - name: Sync to NetBox (Async Mode)
      ansible.builtin.import_role:
        name: arista.avd.netbox_deploy
