type: l2leaf
l2leaf:
  defaults:
    platform: vEOS-lab
    spanning_tree_mode: mstp
  node_groups:
  - group: DC1_L2_LEAF1
    nodes:
    - name: LEAF3C
      id: 1
      mgmt_ip: 172.16.100.108/24
    - name: LEAF3D
      id: 2
      mgmt_ip: 172.16.100.109/24
    - name: LEAF3E
      id: 3
      mgmt_ip: 172.16.100.110/24
    uplink_switches:
    - LEAF3A
    - LEAF3B
