type: l2spine
l2spine:
  defaults:
    platform: cEOSLab
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    mlag_peer_ipv4_pool: 192.168.0.0/24
    mlag_interfaces:
    - Ethernet47
    - Ethernet48
  node_groups:
  - group: SPINE1
    nodes:
    - name: SPINE1
      id: 1
  - group: SPINE2
    nodes:
    - name: SPINE2
      id: 2
