type: l3leaf
l3leaf:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 10.255.0.0/27
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 10.255.1.0/27
    uplink_switches:
    - SPINE1
    - SPINE2
    uplink_ipv4_pool: 10.255.255.0/26
    mlag_peer_ipv4_pool: 10.255.1.64/27
    mlag_peer_l3_ipv4_pool: 10.255.1.96/27
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
  - group: LEAF1A
    nodes:
    - name: LEAF1A
      id: 1
      mgmt_ip: 172.16.100.103/24
    bgp_as: 65101
  - group: LEAF1B
    nodes:
    - name: LEAF1B
      id: 2
      mgmt_ip: 172.16.100.104/24
    bgp_as: 65102
  - group: LEAF2A
    nodes:
    - name: LEAF2A
      id: 3
      mgmt_ip: 172.16.100.105/24
    bgp_as: 65103
  - group: LEAF3A
    nodes:
    - name: LEAF3A
      id: 4
      mgmt_ip: 172.16.100.106/24
    bgp_as: 65104
  - group: LEAF3B
    nodes:
    - name: LEAF3B
      id: 5
      mgmt_ip: 172.16.100.107/24
    bgp_as: 65105
